[build]
publish = "build/dist"
command = "npm run build"

[[headers]]
for = "/*"

[headers.values]
Content-Security-Policy = "default-src 'self'; frame-src https://www.youtube-nocookie.com https://pca.st/;"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "deny"
X-XSS-Protection = "1; mode=block"
